version: '3'
services:
  resource_server_1:
    build:
        context: .
        dockerfile: Dockerfile
    image: oauth2_server_demo
    command: ./run_app.sh
    volumes:
      - .:/code
    ports:
      - "${RESOURCE_SERVER_1_WEB_EXTERNAL_PORT}:8000"
    environment:
      - DJANGO_SETTINGS_MODULE=oauth2_server_demo.settings.resource_server_1
      - AUTH_SERVER_INTROSPECTION_URL=http://auth-server.test:$OAUTH2_SERVER_WEB_EXTERNAL_PORT/o/introspect/
    extra_hosts:
      - auth-server.test:$DOCKER_0_HOST
